# Generated by Django 4.1.4 on 2022-12-16 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('GasCan', '0001_initial'), ('GasCan', '0002_perk_rename_perk_type_perktype'), ('GasCan', '0003_perk_perk_type'), ('GasCan', '0004_alter_perk_cost'), ('GasCan', '0005_rename_perktype_perkclass_perk_perk_class_and_more'), ('GasCan', '0006_sponsor_alter_perk_perk_class_perk_sponsor'), ('GasCan', '0007_sponsor_description'), ('GasCan', '0008_alter_perk_perk_class_alter_perk_sponsor'), ('GasCan', '0009_rename_perk_type_perk_type'), ('GasCan', '0010_vehicletype_perk_vehicle_type'), ('GasCan', '0011_remove_vehicletype_description'), ('GasCan', '0012_weapon_weaponspecialrule'), ('GasCan', '0013_weapon_ammo_weapon_attack_dice_weapon_slots_and_more'), ('GasCan', '0014_vehicletype_sponsor'), ('GasCan', '0015_vehicletype_trailer'), ('GasCan', '0016_alter_perk_options_alter_perkclass_options_and_more'), ('GasCan', '0017_alter_perk_options_sponsor_perk_classes')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerkClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(default=1)),
                ('perk_classes', models.ManyToManyField(blank=True, to='GasCan.perkclass')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('weight', models.CharField(choices=[('Lightweight', 'Lightweight'), ('Middleweight', 'Middleweight'), ('Heavyweight', 'Heavyweight')], max_length=250)),
                ('hull', models.PositiveSmallIntegerField()),
                ('handling', models.PositiveSmallIntegerField()),
                ('max_gear', models.PositiveSmallIntegerField()),
                ('crew', models.PositiveSmallIntegerField()),
                ('build_slots', models.PositiveSmallIntegerField()),
                ('cost', models.PositiveSmallIntegerField()),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GasCan.sponsor')),
                ('trailer', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeaponSpecialRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('range', models.CharField(choices=[('Short', 'Short'), ('Medium', 'Medium'), ('Long', 'Long'), ('Double', 'Double'), ('Dropped', 'Dropped'), ('Small Burst', 'Small Burst'), ('Large Burst', 'Large Burst'), ('Smash', 'Smash'), ('Double/Dropped', 'Double/Dropped'), ('Short/Medium', 'Short/Medium'), ('Short/Medium/Long', 'Short/Medium/Long')], max_length=250)),
                ('ammo', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('attack_dice', models.CharField(blank=True, max_length=10, null=True)),
                ('slots', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sponsor', models.ManyToManyField(blank=True, to='GasCan.sponsor')),
                ('weapon_special_rule', models.ManyToManyField(blank=True, to='GasCan.weaponspecialrule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Perk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('cost', models.PositiveSmallIntegerField()),
                ('type', models.CharField(choices=[('General', 'General'), ('Sponsor', 'Sponsor')], default='General', max_length=250)),
                ('perk_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GasCan.perkclass')),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GasCan.sponsor')),
                ('vehicle_types', models.ManyToManyField(blank=True, to='GasCan.vehicletype')),
            ],
            options={
                'ordering': ['perk_class', 'sponsor', 'cost', 'name'],
            },
        ),
    ]
