# Generated by Django 4.1.4 on 2022-12-07 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GasCan', '0002_perk_rename_perk_type_perktype'),
    ]

    operations = [
        migrations.AddField(
            model_name='perk',
            name='perk_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GasCan.perktype'),
            preserve_default=False,
        ),
    ]
