# Generated by Django 4.1.4 on 2022-12-10 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GasCan', '0003_perk_perk_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perk',
            name='cost',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
