# Generated by Django 4.1.4 on 2022-12-10 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GasCan', '0004_alter_perk_cost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PerkType',
            new_name='PerkClass',
        ),
        migrations.AddField(
            model_name='perk',
            name='perk_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GasCan.perkclass'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perk',
            name='cost',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='perk',
            name='perk_type',
            field=models.CharField(choices=[('General', 'General'), ('Sponsor', 'Sponsor')], default='General', max_length=250),
        ),
    ]
