# Generated by Django 4.1.4 on 2022-12-10 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GasCan', '0005_rename_perktype_perkclass_perk_perk_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='perk',
            name='perk_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GasCan.perkclass'),
        ),
        migrations.AddField(
            model_name='perk',
            name='sponsor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GasCan.sponsor'),
        ),
    ]
