# Generated by Django 4.1.4 on 2022-12-10 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GasCan', '0007_sponsor_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perk',
            name='perk_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GasCan.perkclass'),
        ),
        migrations.AlterField(
            model_name='perk',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GasCan.sponsor'),
        ),
    ]
