# Generated by Django 4.1.4 on 2022-12-12 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GasCan', '0008_alter_perk_perk_class_alter_perk_sponsor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perk',
            old_name='perk_type',
            new_name='type',
        ),
    ]
