# Generated by Django 4.1.4 on 2022-12-13 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GasCan', '0010_vehicletype_perk_vehicle_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicletype',
            name='description',
        ),
    ]
