# Generated by Django 4.1.4 on 2022-12-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GasCan', '0011_remove_vehicletype_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('range', models.CharField(choices=[('Short', 'Short'), ('Medium', 'Medium'), ('Long', 'Long'), ('Double', 'Double'), ('Dropped', 'Dropped'), ('Small Burst', 'Small Burst'), ('Large Burst', 'Large Burst'), ('Double/Dropped', 'Double/Dropped'), ('Short/Medium/Long', 'Short/Medium/Long')], max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeaponSpecialRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
