# Generated by Django 4.1.4 on 2022-12-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GasCan', '0012_weapon_weaponspecialrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='ammo',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weapon',
            name='attack_dice',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='weapon',
            name='slots',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weapon',
            name='sponsor',
            field=models.ManyToManyField(blank=True, to='GasCan.sponsor'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='weapon_special_rule',
            field=models.ManyToManyField(blank=True, to='GasCan.weaponspecialrule'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='range',
            field=models.CharField(choices=[('Short', 'Short'), ('Medium', 'Medium'), ('Long', 'Long'), ('Double', 'Double'), ('Dropped', 'Dropped'), ('Small Burst', 'Small Burst'), ('Large Burst', 'Large Burst'), ('Smash', 'Smash'), ('Double/Dropped', 'Double/Dropped'), ('Short/Medium', 'Short/Medium'), ('Short/Medium/Long', 'Short/Medium/Long')], max_length=250),
        ),
    ]
