# Generated by Django 4.1.4 on 2022-12-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GasCan', '0014_vehicletype_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletype',
            name='trailer',
            field=models.BooleanField(default=False),
        ),
    ]
