# Generated by Django 4.1.4 on 2022-12-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GasCan', '0001_squashed_0017_alter_perk_options_sponsor_perk_classes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='description',
            field=models.TextField(),
        ),
    ]
