# Generated by Django 4.1.4 on 2022-12-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GasCan', '0018_alter_sponsor_options_alter_sponsor_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicletype',
            name='sponsor',
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='sponsors',
            field=models.ManyToManyField(blank=True, to='GasCan.sponsor'),
        ),
    ]
