# Generated by Django 4.1.4 on 2022-12-16 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GasCan', '0020_vehicletype_sponsors_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perk',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perks', to='GasCan.sponsor'),
        ),
        migrations.AlterField(
            model_name='perk',
            name='vehicle_types',
            field=models.ManyToManyField(blank=True, related_name='perks', to='GasCan.vehicletype'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='perk_classes',
            field=models.ManyToManyField(blank=True, related_name='sponsors', to='GasCan.perkclass'),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='sponsors',
            field=models.ManyToManyField(blank=True, related_name='vehicle_types', to='GasCan.sponsor'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='sponsor',
            field=models.ManyToManyField(blank=True, related_name='weapons', to='GasCan.sponsor'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='weapon_special_rule',
            field=models.ManyToManyField(blank=True, related_name='weapons', to='GasCan.weaponspecialrule'),
        ),
    ]
