# Generated by Django 4.1.4 on 2022-12-17 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GasCan', '0023_remove_vehicletype_weight_sort'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicletype',
            options={'ordering': ['weight', 'cost', 'name']},
        ),
    ]
