# Generated by Django 4.1.4 on 2022-12-17 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GasCan', '0025_alter_vehicletype_sponsors_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletype',
            name='sponsors_rule',
            field=models.CharField(blank=True, choices=[('Include', 'Include'), ('Exclude', 'Exclude')], max_length=250, null=True),
        ),
    ]
