# Generated by Django 4.1.4 on 2022-12-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GasCan', '0026_alter_vehicletype_sponsors_rule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weapon',
            options={'ordering': ['cost', 'name']},
        ),
        migrations.RenameField(
            model_name='weapon',
            old_name='weapon_special_rule',
            new_name='weapon_special_rules',
        ),
        migrations.AddField(
            model_name='weapon',
            name='cost',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weapon',
            name='slots',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
