# Generated by Django 4.1.4 on 2022-12-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GasCan', '0027_alter_weapon_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weaponspecialrule',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='weapon',
            name='special_rule',
            field=models.TextField(blank=True, null=True),
        ),
    ]
