# Generated by Django 4.1.4 on 2022-12-17 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GasCan', '0028_alter_weaponspecialrule_options_weapon_special_rule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weapon',
            old_name='sponsor',
            new_name='sponsors',
        ),
    ]
