# Generated by Django 4.1.4 on 2022-12-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GasCan', '0030_alter_perk_name_alter_perkclass_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perk',
            name='name',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='perkclass',
            name='name',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='name',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='name',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='weaponspecialrule',
            name='name',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
    ]
