# Generated by Django 4.1.4 on 2022-12-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GasCan', '0031_alter_perk_name_alter_perkclass_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perk',
            name='name',
            field=models.CharField(default='NoName', max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perkclass',
            name='name',
            field=models.CharField(default='NoName', max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(default='NoName', max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='name',
            field=models.CharField(default='NoName', max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weapon',
            name='name',
            field=models.CharField(default='NoName', max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weaponspecialrule',
            name='name',
            field=models.CharField(default='NoName', max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
