# Generated by Django 4.1.4 on 2022-12-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GasCan', '0032_alter_perk_name_alter_perkclass_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weapon',
            options={'ordering': ['type', 'cost', 'name']},
        ),
        migrations.AddField(
            model_name='weapon',
            name='type',
            field=models.CharField(blank=True, choices=[('Crew', 'Crew'), ('Shooting', 'Shooting'), ('Dropped', 'Dropped')], max_length=250, null=True),
        ),
    ]
