# Generated by Django 4.1.4 on 2022-12-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GasCan', '0033_alter_weapon_options_weapon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='type',
            field=models.CharField(choices=[('Crew', 'Crew'), ('Shooting', 'Shooting'), ('Dropped', 'Dropped')], default='Shooting', max_length=250),
            preserve_default=False,
        ),
    ]
