# Generated by Django 4.1.4 on 2022-12-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GasCan', '0034_alter_weapon_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='WeaponSpecialRule',
            new_name='WeaponUpgradeSpecialRule',
        ),
    ]
