# Generated by Django 4.1.4 on 2022-12-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GasCan', '0035_upgrade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgrade',
            name='build_slots',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upgrade',
            name='cost',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upgrade',
            name='crew_adjust',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upgrade',
            name='handling_adjust',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upgrade',
            name='hull_adjust',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upgrade',
            name='max_gear_adjust',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upgrade',
            name='trailer_adjust',
            field=models.BooleanField(default=False, verbose_name='Is a trailer'),
        ),
        migrations.AddField(
            model_name='upgrade',
            name='upgrade_special_rules',
            field=models.ManyToManyField(blank=True, related_name='upgrades', to='GasCan.weaponupgradespecialrule'),
        ),
    ]
