# Generated by Django 4.1.4 on 2022-12-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GasCan', '0036_upgrade_build_slots_upgrade_cost_upgrade_crew_adjust_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgrade',
            name='special_rule',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upgrade',
            name='sponsors',
            field=models.ManyToManyField(blank=True, related_name='upgrades', to='GasCan.sponsor'),
        ),
    ]
