# Generated by Django 4.1.4 on 2022-12-20 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GasCan', '0037_upgrade_special_rule_upgrade_sponsors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weapon',
            old_name='slots',
            new_name='build_slots',
        ),
    ]
