# Generated by Django 4.1.4 on 2022-12-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GasCan', '0039_alter_upgrade_options_upgrade_has_facing'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgrade',
            name='ammo',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
