# Generated by Django 4.1.4 on 2022-12-20 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GasCan', '0041_upgrade_weight_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upgrade',
            old_name='weight_limit',
            new_name='weight_exclude',
        ),
    ]
