# Generated by Django 4.1.4 on 2022-12-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GasCan', '0042_rename_weight_limit_upgrade_weight_exclude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upgrade',
            name='weight_exclude',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Lightweight'), (2, 'Middleweight'), (3, 'Heavyweight')], null=True),
        ),
    ]
